plugins:
  procourse_community_feedback_enabled:
    default: true
    client: true

  procourse_community_feedback_category:
    default: ""
    client: true

  procourse_community_feedback_textarea_placeholder:
    default: "Tell us about your experience.."
    client: true
